route:
  group_by: ['alertname', 'job']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'telegram'

receivers:
- name: 'telegram'
  telegram_configs:
  - bot_token: "8993961420:AAFJmqPSmVt36jEreFReernyUu3SWPThpHA"
    chat_id: 8241862171
    disable_notifications: false
    parse_mode: 'HTML'
    message: |
      <b>⚠️ ALERT</b>
      <b>Status:</b> {{ .Status }}
      <b>Alert:</b> {{ .CommonLabels.alertname }}
      <b>Severity:</b> {{ .CommonLabels.severity }}
      <b>Instance:</b> {{ .CommonLabels.instance }}
      <b>Description:</b> {{ .CommonAnnotations.description }}
      <b>Summary:</b> {{ .CommonAnnotations.summary }}
      <b>Graph:</b> {{ .ExternalURL }}
